# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwiftU17' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftU17
  
    pod 'SnapKit'
    pod 'Moya'
    pod 'HandyJSON'
    pod 'SVProgressHUD'
    pod 'Kingfisher'
    pod 'MJRefresh'
    pod 'FSPagerView'
    pod 'ESTabBarController-swift'
    pod 'SwipeMenuViewController'

end
