# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwiftU17' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftU17
  pod 'Alamofire', '~> 4.8.0'

  pod 'ESTabBarController-swift', '~> 2.6.4'
  
  pod 'FSPagerView', '~> 0.8.1'
  
  pod 'Kingfisher', '~> 4.10.1'
  
  pod 'MJRefresh', '~> 3.1.15.7'
  
  pod 'Moya', '~> 12.0.1'
  
  pod 'SVProgressHUD', '~> 2.2.5'

  pod 'SnapKit', '~> 4.2.0'
  
  pod 'SwipeMenuViewController', '~> 3.0.0'
  
  pod 'HandyJSON'
  
end
