# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftWeibo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftWeibo
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'YYModel'
    pod 'FMDB'
    pod 'SVProgressHUD'
    pod 'pop'

end
